Truyum_CaseStudy_DotNetCore/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace Truyum_CaseStudy_DotNetCore.Models
{
    public class Cart
    {
        [Key]
        public int Id { get; set; }
        [ForeignKey("MenuItem")]
        public int MenuItemId { get; set; } 
        public MenuItem MenuItem { get; set; }

    }
}

Truyum_CaseStudy_DotNetCore/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using System.ComponentModel.DataAnnotations;
namespace Truyum_CaseStudy_DotNetCore.Models
{
    public class Category
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Truyum_CaseStudy_DotNetCore/Models/ErrorViewModel.cs
using System;

namespace Truyum_CaseStudy_DotNetCore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Truyum_CaseStudy_DotNetCore/Models/MenuItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Truyum_CaseStudy_DotNetCore.Models
{
    public class MenuItem
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public double Price { get; set; }

        public bool Active { get; set; }

        [Display(Name="Free Delivery")]
        public bool DeliveryStatus { get; set; }

        [Display(Name="Date Of Launch")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}",ApplyFormatInEditMode = true)]
        public DateTime LaunchDate { get; set; }

        [ForeignKey("category")]
        public int CategoryId { get; set; }
        public Category category { get; set; }
        
    }
}

Truyum_CaseStudy_DotNetCore/Models/TruYumContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

//using System.Data.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
namespace Truyum_CaseStudy_DotNetCore.Models
{
    public static class ModelBuilderExtensions
    {
        public static void RemovePluralizingTableNameConvention(this ModelBuilder modelBuilder)
        {
            foreach (IMutableEntityType entity in modelBuilder.Model.GetEntityTypes())
            {
                entity.SetTableName(entity.DisplayName());
            }
        }
    }
    public class TruYumContext:DbContext
    {

        public TruYumContext(DbContextOptions<TruYumContext> options) : base(options)
        {

        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
           // modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
            modelBuilder.RemovePluralizingTableNameConvention();
        }

        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<MenuItem> MenuItems { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
    }
}

Truyum_CaseStudy_DotNetCore/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Truyum_CaseStudy_DotNetCore.Models;

namespace Truyum_CaseStudy_DotNetCore.Controllers
{
    public class AdminController : Controller
    {
        private readonly TruYumContext context;
        public AdminController(TruYumContext context)
        {
            this.context = context;
        }
        public IActionResult Index()
        {
            //var context = new TruYumContext();
            //var item = from items in context.MenuItems
              //         select items;
            var category = from i in context.MenuItems.Include(i => i.category)
                           select i;
            return View(category.ToList());
        }

        public IActionResult Create()
        {
            List<Category> categoryList = new List<Category>();
            categoryList = (from category in context.Categories
                            select category).ToList();
            categoryList.Insert(0, new Category { Id = 0, Name = "select" });
            ViewBag.categories = categoryList;
            return View();
        } 

        [HttpPost]
        public IActionResult Create(MenuItem menu)
        {
            if (!ModelState.IsValid)
                return View(menu);
            context.MenuItems.Add(menu);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id)
        {
            List<Category> categoryList = new List<Category>();
            categoryList = (from category in context.Categories
                            select category).ToList();
            categoryList.Insert(0, new Category { Id = 0, Name = "select" });
            ViewBag.categories = categoryList;
            var menuItem = context.MenuItems.Find(id);
            if (menuItem == null) return NotFound();
            return View(menuItem);
        }



        [HttpPost]
        public IActionResult Edit(MenuItem menuItem)
        {
            if (!ModelState.IsValid)
                return View(menuItem);
            context.Attach(menuItem);
            context.Entry(menuItem).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Truyum_CaseStudy_DotNetCore/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Truyum_CaseStudy_DotNetCore.Models;
namespace Truyum_CaseStudy_DotNetCore.Controllers
{
    public class CartController : Controller
    {
        private readonly TruYumContext context;
        public CartController(TruYumContext context)
        {
            this.context = context;
        }
        public IActionResult Index()
        {
            var cartItems = from i in context.Carts.Include(m => m.MenuItem)
                            select i;
            return View(cartItems.ToList());
        }

        public IActionResult Remove(int id)
        {
            var cartItem = context.Carts.Find(id);
            if (cartItem == null) return NotFound();
            context.Carts.Remove(cartItem);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Truyum_CaseStudy_DotNetCore/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Truyum_CaseStudy_DotNetCore.Models;

namespace Truyum_CaseStudy_DotNetCore.Controllers
{
    public class CustomerController : Controller
    {
        private readonly TruYumContext context;
        public CustomerController(TruYumContext context)
        {
            this.context = context;
        }
        public IActionResult Index()
        {
            var category = from i in context.MenuItems.Include(i => i.category)
                           select i;
            return View(category.ToList());
            
        }

       
        public ActionResult Add(int id)
        {
            //var item = context.MenuItems.Find(id);
            var item = context.MenuItems.FirstOrDefault(s => s.Id == id);
            if (item == null)
                return NotFound();
            Cart cart = new Cart();
            cart.MenuItemId = item.Id;
            var c = context.Carts.Add(cart);
            context.SaveChanges();

            return RedirectToAction("Index","Cart");
        }
    }
}

Truyum_CaseStudy_DotNetCore/Controllers/MenuItemsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Truyum_CaseStudy_DotNetCore.Controllers
{
    public class MenuItemsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Truyum_CaseStudy_DotNetCore/Views/Admin/Create.cshtml
@model MenuItem
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>
<h3>MenuItem</h3>
<form asp-controller="Admin" asp-action="Create" class="form-horizontal">
    <div asp-validation-summary="All"></div>
    <div class="form-group">
        <div class="row mb-3">
            <label asp-for="Name" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-3">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name"></span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="row mb-3">
            <label asp-for="DeliveryStatus" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-3">
                <div class="form-check">
                    <input class="form-check-input" asp-for="DeliveryStatus" />
                </div>
            </div>

        </div>
    </div>
    <div class="form-group">
        <div class="row mb-3">
            <label asp-for="Price" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-3">
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price"></span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="row mb-3">
            <label asp-for="LaunchDate" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-3">
                <input asp-for="LaunchDate" class="form-control" />
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="row mb-3">
            <label asp-for="Active" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-3">
                <div class="form-check">
                    <input class="form-check-input" asp-for="Active" />
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="row mb-3">
            <label asp-for="CategoryId" class="col-sm-2 col-form-label">Category</label>
            <div class="col-sm-3">
                @*<input asp-for="LaunchDate" class="form-control" />*@
                @* @Html.DropDownListFor() *@
                @*<select asp-for="category" asp-items="@ViewBag.categories">*@
                <select asp-for="CategoryId" asp-items="@(new SelectList(ViewBag.categories,"Id","Name"))"></select>
            </div>
        </div>
    </div>
    <input type="submit" class="btn btn-light btn-outline-secondary" value="Save" />


</form>


<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

Truyum_CaseStudy_DotNetCore/Views/Admin/Edit.cshtml
@model MenuItem
@{
    ViewData["Title"] = "Edit";
}



<h1>Edit</h1>
<h3>Menu Item</h3>

<form asp-controller="Admin" asp-action="Edit" class="form-horizontal">
    <div asp-validation-summary="All"></div>
    @Html.HiddenFor(Model => Model.Id)


   
    <div class="form-group">
        <div class="row mb-3">
            <label asp-for="@Model.Name" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-3">
                <input asp-for="@Model.Name" class="form-control" />
                <span asp-validation-for="@Model.Name"></span>
            </div>
        </div>
    </div>


   
    <div class="form-group">
        <div class="row mb-3">
            <label asp-for="@Model.DeliveryStatus" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-3">
                <div class="form-check">
                    <input class="form-check-input" asp-for="@Model.DeliveryStatus" />
                </div>
            </div>

        </div>
    </div>


    <div class="form-group">
        <div class="row mb-3">
            <label asp-for="@Model.Price" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-3">
                <input asp-for="@Model.Price" class="form-control" />
                <span asp-validation-for="@Model.Price"></span>
            </div>
        </div>
    </div>


    <div class="form-group">
        <div class="row mb-3">
            <label asp-for="@Model.LaunchDate" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-3">
                <input asp-for="@Model.LaunchDate" class="form-control" />
            </div>
        </div>
    </div>


    <div class="form-group">
        <div class="row mb-3">
            <label asp-for="@Model.CategoryId" class="col-sm-2 col-form-label">Category</label>
            <div class="col-sm-3">
                <select asp-for="@Model.CategoryId" asp-items="@(new SelectList(ViewBag.categories,"Id","Name"))"></select>
            </div>
        </div>
    </div>


    <div class="form-group">
        <div class="row mb-3">
            <label asp-for="@Model.Active" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-3">
                <div class="form-check">
                    <input class="form-check-input" asp-for="@Model.Active" />
                </div>
            </div>
        </div>
    </div>


    <input type="submit" value="Save" />
    <a asp-controller="Admin" asp-action="Index">Back to list</a>
 </form>

    
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

Truyum_CaseStudy_DotNetCore/Views/Admin/Index.cshtml
@model List<MenuItem>
@{
    ViewData["Title"] = "Index";
}

<h1>Menu Items</h1>
<a asp-controller="Admin" asp-action="Create">Create New</a>
<table class="table">
    <tr>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">Active</th>
        <th scope="col">Date of Launch</th>
        <th scope="col">Name</th>
        <th scope="col">Free Delivery</th>
        <th scope="col">Action</th>
    </tr>
   @foreach(var item in Model)
            {
                    <tr>
                        <td>@item.Name</td>
                        <td>@item.Price</td>
                        <td>
                            <input type="checkbox" checked="@item.Active" onclick="return false;"/>
                        </td>  
                        <td>@item.LaunchDate.ToShortDateString()</td>
                        <td>@item.category.Name</td>
                        <td>
                            <input type="checkbox" checked="@item.DeliveryStatus" onclick="return false;"/>
                        </td>
                        <td><a asp-controller="Admin" asp-action="Edit" asp-route-id="@item.Id">Edit</a></td>
                    </tr>
            }
</table>



Truyum_CaseStudy_DotNetCore/Views/Cart/Index.cshtml
@model List<Cart>
@{
    ViewData["Title"] = "Index";
}

<h2>View Cart</h2>
@if (Model.Count == 0)
{
    <p>No items in cart.<a asp-controller="Customer" asp-action="Index">View menu items</a></p>
}
else
{
<table class="table">
    <tr>
        <th scope="col">Name</th>
        <th scope="col">Free Delivery</th>
        <th scope="col">Price</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.MenuItem.Name</td>
            <td>
                <input type="checkbox" checked="@item.MenuItem.DeliveryStatus" onclick="return false;" />
            </td>
            <td>@item.MenuItem.Price</td>
            <td><a asp-controller="Cart" asp-action="Remove" asp-route-id="@item.Id">Remove</a></td>
        </tr>
    }
</table>
}

Truyum_CaseStudy_DotNetCore/Views/Customer/Index.cshtml
@model List<MenuItem>
@{
    ViewData["Title"] = "Index";
}

<h2>Menu Items</h2>

<table class="table">
    <tr>
        <th scope="col">Name</th>
        <th scope="col">Free Delivery</th>
        <th scope="col">Price</th>
        <th scope="col">Name</th>
        <th scopr="col">Action</th>
    </tr>
    @foreach (var item in Model)
    { 
        <tr>
            <td>@item.Name</td>
            <td>
                <input type="checkbox" checked="@item.DeliveryStatus" onclick="return false;" />
            </td>
            <td>@item.Price</td>
            <td>@item.category.Name</td>
            <td><a asp-controller="Customer" asp-action="Add" asp-route-id="@item.Id">Add to Cart</a></td>
        </tr>
    }
   
</table>

Truyum_CaseStudy_DotNetCore/Views/MenuItems/Index.cshtml

@{
    ViewData["Title"] = "Index";
}


<div class="text-center">
    <h2 class="display-4">Welcome to Truyum Application</h2>
</div>

Truyum_CaseStudy_DotNetCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Truyum_CaseStudy_DotNetCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark text-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="MenuItems" asp-action="Index">TruYum</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Admin" asp-action="Index">Menu Item-Admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Customer" asp-action="Index">Menu Item</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Cart" asp-action="Index">Cart</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Truyum - <a asp-area="" asp-controller="" asp-action="">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>